#Basic Settings
title: Bing Image Download
description: "Simple command line application which will retrieve the latest set of Bing images."
url: https://bing-images.blyth.me.uk
githubRepo: https://github.com/BlythMeister/BingImageDownload
author: BlythMeister
logo: /images/icon.png
lang: en_GB
enableCsp: true

GoogleAnalytics: G-JZDFPBLNZE

#Webmaster tools
webmaster_verifications:
  google: 
  bing: 

#Social
twitter:
    username: BlythMeister
    card: summary

facebook:
   app_id: 1934053506806190
   publisher: 285001657
   admins: 285001657

social:
    name: Chris Blyth
    links:
        - https://www.twitter.com/BlythMeister
        - https://www.linkedin.com/in/chris-blyth/
        - https://github.com/BlythMeister

#Link format
permalink: pretty

#Pagination
paginate: 5
paginate_path: "/posts/page:num"

#Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: /images/icon.png

#Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
